### ISSUE TITLE
[CC1.10.017] As a teacher, I want to know per period what students have registered

### ISSUE THREAD

**Issue by philschatz** [philschatz/gh-demo#488]
Some text describing the story. Discussion about change requests go directly here as comments.
![image](https://cloud.githubusercontent.com/assets/253202/12076781/0bc43d30-b189-11e5-9501-fa64af30b53b.png)
# TODO
- [x] create mockups (some UX work)
- [x] Item for FE to implement
- [x] another item for FE to implement

**Comment by philschatz** [comment]
Looks Great!
